---
vector_version: "0.32.1-1"
vector_config:
  sources:
    dummy_logs:
      type: demo_logs
      format: syslog
      interval: 1
  sinks:
    my_sink:
      type: console
      inputs:
        - dummy_logs
      target: stdout
      encoding:
        codec: json
  api:
    enabled: true
    address: "0.0.0.0:8686"