- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/latest/vector_{{ vector_version }}_amd64.deb"
    dest: "./vector_{{ vector_version }}_amd64.deb"
- name: Install vector package
  become: true
  ansible.builtin.apt:
    deb: "./vector_{{ vector_version }}_amd64.deb"
