- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/latest/vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
    dest: "./vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
- name: Install vector package
  become: true
  ansible.builtin.yum:
    name:
      - "./vector-{{ vector_version }}.{{ ansible_architecture }}.rpm"
