---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: local/c7-systemd
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../resources/inventory/hosts.yml
      group_vars: ../resources/inventory/group_vars/
      host_vars: ../resources/inventory/host_vars/
  playbooks:
    verify: ../resources/tests/verify.yml
verifier:
  name: ansible
