---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../resources/inventory/hosts.yml
      group_vars: ../resources/inventory/group_vars/
      host_vars: ../resources/inventory/host_vars/
verifier:
  name: ansible
scenario:
  test_sequence:
  - destroy
  - create
  - converge
  - destroy